name: Generate Linux exe for Terraformx Apply Action
on: [push]
# on:
#   push:
#     tags:
#       - "release/github_action_terraformx_apply/v[012].[0-9]+.[0-9]+"
      
jobs:
  generate_linux_exe:
    runs-on: ubuntu-latest
    name: Generate Linux exe for Terraformx Apply Action
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.1"

      - name: Install Dependencies and PyInstaller
        run: pip install -r $GITHUB_WORKSPACE/requirements.txt
        shell: bash

      - name: Generate linux exe with pyinstaller
        working-directory: actions
        run: |
          pyinstaller --onefile github_action_terraformx_apply.py -p $GITHUB_WORKSPACE -y
          mv dist/github_action_terraformx_apply dist/apply

      - name: Clone action repo
        run: git clone https://${{ github.repository_owner }}:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository_owner }}/action_terraformx_apply.git action_repo

      - name: Create branch
        working-directory: action_repo
        run: git checkout -b update_exe

      - name: Update exe
        working-directory: actions
        run: |
          cp dist/apply ../action_repo/exe/apply

      - name: Commit and push
        working-directory: action_repo
        run: |
          git config user.email "test@gmail.com"
          git config user.name "test"

          git add .
          git commit -m "Update action exe"
          git push --set-upstream origin update_exe

      - name: Create PR
        working-directory: action_repo
        run: |
          echo "${{ secrets.ACCESS_TOKEN }}" > token.txt
          gh auth login --with-token < token.txt
          
          gh pr create --body "" --title "Update exe version" --head "update_exe" --base "main"
