name: Generate Linux exe for Terraformx Destroy Action
on:
  push:
    tags:
      - "release/github_action_terraformx_destroy/v[012].[0-9]+.[0-9]+"

jobs:
  generate_linux_exe:
    runs-on: ubuntu-latest
    name: Generate Linux exe for Terraformx Destroy Action
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.1"

      - name: Install Dependencies and PyInstaller
        run: pip install -r $GITHUB_WORKSPACE/requirements.txt
        shell: bash

      - name: Generate linux exe with pyinstaller
        working-directory: actions
        run: |
          pyinstaller --onefile github_action_terraformx_destroy.py -p $GITHUB_WORKSPACE -y
          mv /dist/github_action_terraformx_destroy /dist/destroy

        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: destroy
          path: actions/dist/github_action_terraformx_destroy
