name: Generate Linux exe for Terraformx Apply Action
on: [push]
# on:
#   push:
#     tags:
#       - "release/github_action_terraformx_apply/v[012].[0-9]+.[0-9]+"
      
jobs:
  generate_linux_exe:
    runs-on: ubuntu-latest
    name: Generate Linux exe for Terraformx Apply Action
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.1"

      - name: Install Dependencies and PyInstaller
        run: pip install -r $GITHUB_WORKSPACE/requirements.txt
        shell: bash

      - name: Generate linux exe with pyinstaller
        working-directory: actions
        run: |
          pyinstaller --onefile github_action_terraformx_apply.py -p $GITHUB_WORKSPACE -y
          mv dist/github_action_terraformx_apply dist/apply

      - name: Clone action repo
        run: git clone https://github.com/iSoBored/action_terraformx_apply.git action_repo

      - name: Create branch
        working-directory: action_repo
        run: git checkout -b update_exe

      - name: Update exe
        working-directory: actions
        run: |
          cp dist/apply ../action_repo/apply
          ls
